### ISSUE TITLE
Do you have a c# version of this?

### ISSUE THREAD

**Issue by nigel-dewar** [microsoftgraph/nodejs-apponlytoken-rest-sample#10]
Do you have a c# version of this?

Im not that savvy with node.js

Cheers

**Comment by DianeD** [comment]
Thanks @nigel-dewar . I added this to our list of app ideas. Would a console app be okay?

**Comment by nigel-dewar** [comment]
Yes that would be great, thank you very much,!

**Comment by DianeD** [comment]
Added to the list, thanks again!
