### ISSUE TITLE
Extend Example for Adding SharePoint List Item

### ISSUE THREAD

**Issue by ehalsey** [microsoftgraph/nodejs-apponlytoken-rest-sample#11]
I'm trying to extend this example to add a SharePoint list item but I'm getting -2147024891, System.UnauthorizedAccessException "Access denied. You do not have permission to perform this action or access this resource." with app only token.  It's not clear to me if I need to give app perms for both "Microsoft Graph" and "Office 365 SharePoint Online".

![2017-01-09_17-09-27](https://cloud.githubusercontent.com/assets/14900980/21790122/e5c32980-d68e-11e6-892f-9c973aa257d1.png)

![2017-01-09_17-09-53](https://cloud.githubusercontent.com/assets/14900980/21790128/ee37e1c8-d68e-11e6-8631-35aceff501be.png)

graph.createItem 
https://github.com/ehalsey/alexa-nodejs-apponlytoken-rest-sample-master/blob/master/graph.js

**Comment by DianeD** [comment]
Hi @ehalsey . Looking into this.

**Comment by DianeD** [comment]
Hi @ehalsey . App-only scenarios are not supported with SharePoint (or OneDrive) via Microsoft Graph right now. You would need to use ADAL to request a token for the SharePoint endpoint (after discovering it via Graph) and make calls directly to SharePoint's API.

**Comment by bsdaniel** [comment]
How would this apply for calling the find meeting times API? I am very confused with this portion of the application. Would it be a similar call to as creating a event on the users calendars? Any help would be great. Thanks.
