### ISSUE TITLE
Certificate requirement

### ISSUE THREAD

**Issue by himanshuphirke** [microsoftgraph/nodejs-apponlytoken-rest-sample#12]
Doesn't this app require a  X.509 certificate to obtain app-only access token?

**Comment by lousimonetti** [comment]
No, you can generate an App secret in the Azure AD portal for you application.  That can be used in place of the X.509 certificate for the app-only call. 
The sample provided on the documentation site, shows the call to get the app-only auth token via a POST like this:
// Line breaks are for legibility only.

POST /{tenant}/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

client_id=535fb089-9ff3-47b6-9bfb-4f1264799865
&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
&client_secret=qWgdYAmab0YSkuL1qKv5bPX
&grant_type=client_credentials
 
https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_service

**Comment by himanshuphirke** [comment]
@lousimonetti 
I had used token endpoint (available in azure portal after app registration) for getting the access token.

Unfortunately, the screenshots in the documentation do not match with actual sites which makes the work difficult.

Thanks for responding.
