### ISSUE TITLE
Using Microsoft Graph with client credentials and message subscriptions

### ISSUE THREAD

**Issue by rafimor** [microsoftgraph/nodejs-apponlytoken-rest-sample#13]
Hi.  Thank you for this sample code, it's very helpful.   I have the example running no problem creating the test calendar events.
My goal is to use client credentials and Graph subscriptions for messages, for several users in my tenant.   I modified the code to create a subscription for messages, but I get a failure of "Unsupported segment type".

Does graph support client credentials for subscriptions?  If yes, am I doing something wrong?

 "error": {
    "code": "BadRequest",
    "message": "Unsupported segment type. ODataQuery: users/<user-id-removed>/subscriptions",
    "innerError": {
      "request-id": "e92caf14-0343-40b0-8720-30946d7fd236",
      "date": "2018-05-17T17:53:34"
    }
  }

Here's my subscribe function:

graph.subscribe = function (token, userid) {

    var subscription = {
      changeType: 'Created',
      notificationUrl: 'my notification url',
      resource: '/users/<userid removed>/messages',
      clientState: 'blah'
    };

    request.post({
      url: 'https://graph.microsoft.com/v1.0/users/<userid removed>/subscriptions',
      headers: {
        'content-type': 'application/json',
        authorization: 'Bearer ' + token
      },
      body: JSON.stringify(subscription)
    }, function (err, response, body) {
      if (err) {
        console.error('>>> Application error: ' + err);
      } else {
        console.log('>>> Subscription returned ' + body);
      }
    });
};

**Comment by rafimor** [comment]
I got the answer:

The POST should be issued to the /v1.0/subscriptions endpoint, not /v1.0/users/{upn}/subscriptions.

**Comment by bsdaniel** [comment]
When you ran the sample app you went to the localhost:3000 url correct?
